name: New issues
on:
  issues:
    types: [ opened, edited, reopened ]
jobs:
  add-to-project-board:
    name: Add issue to project board
    runs-on: ubuntu-latest
    steps:
      - name: Add new issues to project board
        uses: cucumber/action-add-issues-to-project@main
        with:
          gitub_token: ${{ secrets.NEW_ISSUES_GITHUB_TOKEN }}
          github_project_title: New issues
          github_org: cucumber
