name: Release NPM module

on:
  push:
    branches: [release/*]

jobs:
  publish-javascript:
    name: Release NPM module
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: cucumber/action-publish-npm@v1.0.0
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          working-directory: javascript
