name: Create GitHub Release

on:
  push:
    branches: [release/*]

jobs:
  create-github-release:
    name: Create GitHub Release and Git tag
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: cucumber/actions-create-github-release@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
