name: test-python

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - python/**
      - testdata/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - python/**
      - testdata/**
      - .github/**

jobs:
  test-python-linting:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: python
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        enable-cache: true
        python-version: "3.14"
        version: "0.11.18"

    - name: Linting
      run: uvx pre-commit run --all-files

  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - os: windows-latest
            python-version: "3.10"
          - os : macos-latest
            python-version: "3.10"
    defaults:
      run:
        working-directory: python
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
        version: "0.11.18"

    - name: Run pytest
      run: uv run --with pytest-github-actions-annotate-failures pytest -p no:sugar --quiet tests/
